### 导入数据

#### 得到CaseStudy需要的数据

In [1]:
import pandas as pd
Cdata = pd.read_csv("C:/Users/HUAWEI/Desktop/DPIs/data/Drug_Protein_Num.csv",header=None)
Cdata.head()

   0    1
0  0  984
1  0  985
2  0  986
3  1  987
4  1  988

In [2]:
Pr_name = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/data/protein_name.csv')
Pr_name.head()

   Unnamed: 0               protein
0         984  9606.ensp00000364709
1         985  9606.ensp00000364731
2         986  9606.ensp00000233838
3         987  9606.ensp00000410294
4         988  9606.ensp00000393312

In [3]:
Pr_name = Pr_name.rename(columns={'Unnamed: 0': 'PrID'})
Pr_name.head()

   PrID               protein
0   984  9606.ensp00000364709
1   985  9606.ensp00000364731
2   986  9606.ensp00000233838
3   987  9606.ensp00000410294
4   988  9606.ensp00000393312

#### 输入所要研究的Drug编号

In [4]:
# 本次使用的Drug有：Risperidone db00734 275; Haloperidol db00502 182 
# Clozapine DB00363 120
# Pioglitazone DB01132 436
# Caffeine  DB00201 56
# drug_list = [275,182]
#drug_list = [56,120,436]
import numpy as np
drug_list = list(np.random.randint(0, 985, 985)) ## 选取全部进行训练
global Full_Case_data
Full_Case_data = pd.DataFrame()
for i in drug_list:
    Case_data= Cdata.loc[Cdata[0] == i]
    Case_data = Case_data.rename(columns={1: 'PrID'})
    dd2 = pd.merge(Pr_name,Case_data,how='left',on='PrID')
    dd2 = dd2[~dd2[0].isin([i])]
    dd2 = dd2.drop(['protein',0],axis=1)
    dd2['DrugID']=i
    dd2.insert(0, 'DrugID', dd2.pop('DrugID'))
    Full_Case_data = Full_Case_data.append(dd2)
Full_Case_data.head()

   DrugID  PrID
0      10   984
1      10   985
2      10   986
3      10   987
4      10   988

In [5]:
Full_Case_data.to_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/Casestudy_Num_all.csv',header=0,index=0)

### 计算GCN Feaure

#### 导入特征

In [6]:
node_features = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/data/Drug_Protein_Attribute.csv',header = None) 
node_features = node_features.iloc[:,1:]
node_features.head()

,1,2,3,4,5,6,7,8,9,10,...,55,56,57,58,59,60,61,62,63,64
0,-0.007599,-0.007655,-0.003703,-0.007203,0.002032,0.006483,0.005779,-0.008866,-0.00496,0.005712,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
1,-0.007599,-0.007655,-0.003703,-0.007203,0.002032,0.006483,0.005779,-0.008866,-0.00496,0.005712,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
2,-0.007599,-0.007655,-0.003703,-0.007203,0.002032,0.006483,0.005779,-0.008866,-0.00496,0.005712,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
3,-0.007599,-0.007655,-0.003703,-0.007203,0.002032,0.006483,0.005779,-0.008866,-0.00496,0.005712,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
4,1.180584,0.526513,0.793145,-0.245426,-0.220634,0.559357,1.059898,0.148331,-0.98174,-0.789687,...,0.003815,-0.553314,0.003378,0.335591,0.143528,-1.134055,0.62961,0.330191,0.377519,-0.798777

In [7]:
#### 设置标签
import numpy as np
DTIs= pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/data/Drug_Protein_Num.csv',header = None) 
labels = pd.DataFrame(np.random.rand(max(DTIs[1])+1,1))#pd.DataFrame(np.random.rand(max(NLMI_num),1))
labels[0:max(DTIs[0])+1]=0
labels[max(DTIs[0])+1:]=1
labels = labels[0] # 提取节点标签列
labels[:5]

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: 0, dtype: float64

In [8]:
# 构建初始的邻接矩阵 #('./data/DDI_train'+str(i)+'.csv')
def load_file_as_Adj_matrix(filename):
    import scipy.sparse as sp
    DTIs_train = pd.read_csv(filename,header=None)
    if max(DTIs_train[1]) != 1618:
        relation_matrix = np.zeros((1618+1,1618+1))
    else:
        relation_matrix = np.zeros((max(DTIs_train[1]+1),max(DTIs_train[1]+1)))
    for i, j in np.array(DTIs_train):
        lnc, mi = int(i), int(j)
        relation_matrix[lnc, mi] = 1
    Adj = sp.csr_matrix(relation_matrix, dtype=np.float32)
    return Adj

In [9]:
# 构建GCN训练需要的邻接方阵
import scipy.sparse as sp
import torch
def load_data(adj,node_features,node_labels):
  features = sp.csr_matrix(node_features, dtype=np.float32)  # 储存为csr型稀疏矩阵
  # build symmetric adjacency matrix   论文里A^=(D~)^0.5 A~ (D~)^0.5这个公式
  # adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)
  # 对于无向图，邻接矩阵是对称的。上一步得到的adj是按有向图构建的，转换成无向图的邻接矩阵需要扩充成对称矩阵
  features = normalize(features)
  adj = normalize(adj + sp.eye(adj.shape[0]))   # eye创建单位矩阵，第一个参数为行数，第二个为列数
  # 对应公式A~=A+IN
  # 分别构建训练集、验证集、测试集，并创建特征矩阵、标签向量和邻接矩阵的tensor，用来做模型的输入
  idx_train = range(500)
  idx_val = range(500, 660)
  idx_test = range(660, int(adj.shape[0]))  
  features = torch.FloatTensor(np.array(features.todense()))  # tensor为pytorch常用的数据结构
  labels = torch.LongTensor(np.array(node_labels))
  adj = sparse_mx_to_torch_sparse_tensor(adj)   # 邻接矩阵转为tensor处理
  idx_train = torch.LongTensor(idx_train)
  idx_val = torch.LongTensor(idx_val)
  idx_test = torch.LongTensor(idx_test)
  return adj, features, labels, idx_train, idx_val, idx_test  
def normalize(mx):
  """Row-normalize sparse matrix"""
  rowsum = np.array(mx.sum(1))  # 对每一行求和
  r_inv = np.power(rowsum, -1).flatten()  # 求倒数
  r_inv[np.isinf(r_inv)] = 0.  # 如果某一行全为0，则r_inv算出来会等于无穷大，将这些行的r_inv置为0
  r_mat_inv = sp.diags(r_inv)  # 构建对角元素为r_inv的对角矩阵
  mx = r_mat_inv.dot(mx)
  # 用对角矩阵与原始矩阵的点积起到标准化的作用，原始矩阵中每一行元素都会与对应的r_inv相乘，最终相当于除以了sum
  return mx

def accuracy(output, labels):
  preds = output.max(1)[1].type_as(labels) # 使用type_as(tesnor)将张量转换为给定类型的张量。
  correct = preds.eq(labels).double()  # 记录等于preds的label eq:equal
  correct = correct.sum()
  return correct / len(labels)

def sparse_mx_to_torch_sparse_tensor(sparse_mx):    # 把一个sparse matrix转为torch稀疏张量
  """
  numpy中的ndarray转化成pytorch中的tensor : torch.from_numpy()
  pytorch中的tensor转化成numpy中的ndarray : numpy()
  """
  sparse_mx = sparse_mx.tocoo().astype(np.float32)
  indices = torch.from_numpy(np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
  # 不懂的可以去看看COO性稀疏矩阵的结构
  values = torch.from_numpy(sparse_mx.data)
  shape = torch.Size(sparse_mx.shape)
  return torch.sparse.FloatTensor(indices, values, shape)

In [10]:
import math
import torch
from torch.nn.parameter import Parameter
from torch.nn.modules.module import Module

class GraphConvolution(Module):

    # 初始化层：输入feature，输出feature，权重，偏移
    def __init__(self, in_features, out_features, bias=True):
        super(GraphConvolution, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(torch.FloatTensor(in_features, out_features))  # FloatTensor建立tensor
        # 常见用法self.v = torch.nn.Parameter(torch.FloatTensor(hidden_size))：
        # 首先可以把这个函数理解为类型转换函数，将一个不可训练的类型Tensor转换成可以训练的类型parameter并将这个parameter
        # 绑定到这个module里面，所以经过类型转换这个self.v变成了模型的一部分，成为了模型中根据训练可以改动的参数了。
        # 使用这个函数的目的也是想让某些变量在学习的过程中不断的修改其值以达到最优化。
        if bias:
            self.bias = Parameter(torch.FloatTensor(out_features))
        else:
            self.register_parameter('bias', None)
            # Parameters与register_parameter都会向parameters写入参数，但是后者可以支持字符串命名
        self.reset_parameters()

    # 初始化权重
    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        # size()函数主要是用来统计矩阵元素个数，或矩阵某一维上的元素个数的函数  size（1）为行
        self.weight.data.uniform_(-stdv, stdv)  # uniform() 方法将随机生成下一个实数，它在 [x, y] 范围内
        if self.bias is not None:
            self.bias.data.uniform_(-stdv, stdv)

    '''
    前馈运算 即计算A~ X W(0)
    input X与权重W相乘，然后adj矩阵与他们的积稀疏乘
    直接输入与权重之间进行torch.mm操作，得到support，即XW
    support与adj进行torch.spmm操作，得到output，即AXW选择是否加bias
    '''
    def forward(self, input, adj):
        support = torch.mm(input, self.weight)
        # torch.mm(a, b)是矩阵a和b矩阵相乘，torch.mul(a, b)是矩阵a和b对应位相乘，a和b的维度必须相等
        output = torch.spmm(adj, support)
        if self.bias is not None:
            return output + self.bias 
        else:
            return output
#通过设置断点，可以看出output的形式是0.01，0.01，0.01，0.01，0.01，#0.01，0.94]，里面的值代表该x对应标签不同的概率，故此值可转换为#[0,0,0,0,0,0,1]，对应我们之前把标签onthot后的第七种标签

    def __repr__(self):
        return self.__class__.__name__ + ' (' \
               + str(self.in_features) + ' -> ' \
               + str(self.out_features) + ')'

In [11]:
import torch.nn as nn
import torch.nn.functional as F
class GCN(nn.Module):
  def __init__(self, nfeat, nhid, nclass, dropout):
    # 底层节点的参数，feature的个数；隐层节点个数；最终的分类数
    super(GCN, self).__init__()  #  super()._init_()在利用父类里的对象构造函数
    self.gc1 = GraphConvolution(nfeat, nhid)   # gc1输入尺寸nfeat，输出尺寸nhid
    self.gc2 = GraphConvolution(nhid, nclass)  # gc2输入尺寸nhid，输出尺寸ncalss
    self.dropout = dropout
    self.weight = Parameter(torch.FloatTensor(nfeat, nhid))  # FloatTensor建立tensor
    # 输入分别是特征和邻接矩阵。最后输出为输出层做log_softmax变换的结果
  def forward(self, x, adj):
    x = F.relu(self.gc1(x, adj))   # adj即公式Z=softmax(A~Relu(A~XW(0))W(1))中的A~
    x2 = F.dropout(x, self.dropout, training = self.training)  # x要dropout
    x2 = self.gc2(x2, adj)
    return F.log_softmax(x2, dim = 1), x2   #, x  # 参数dim=1表示对每一行求softmax，那么每一行的值加起来都等于1。

In [12]:
# Training settings
learning_rate = 0.01
weight_decay = 5e-4
epoch_num = 200
dropout = 0.02
#in_size = node_features  #设置输入层的维数
hi_size = 64 # 16 #设置隐藏层的维数

Adj = load_file_as_Adj_matrix('C:/Users/HUAWEI/Desktop/DPIs/data/Drug_Protein_Num.csv')
adj, train_features, trian_labels, idx_train, idx_val, idx_test = load_data(Adj,node_features,labels)
model = GCN(nfeat=train_features.shape[1],
        nhid=hi_size,
        nclass= 16,#labels.max().item() + 1,
        dropout=dropout)
model.train()
global Emdebding_train, output
output, Emdebding_train = model(train_features, adj)
Emdebding_GCN = pd.DataFrame(Emdebding_train.detach().numpy())
GCN_A = pd.concat([Emdebding_GCN, node_features], axis=1)
GCN_A.to_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/Emdebding_GCN.csv', header=None,index=False)
del Adj, adj, train_features, trian_labels, idx_train, idx_val, idx_test, output
GCN_A.head()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,0.140711,0.051194,0.195033,-0.212925,0.000013,0.099168,0.282278,-0.134109,-0.133199,-0.073208,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
1,0.134333,0.054086,0.195243,-0.208572,-0.004487,0.093488,0.286102,-0.126171,-0.129022,-0.070789,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
2,0.129165,0.050483,0.190854,-0.200663,0.004040,0.084834,0.284004,-0.126870,-0.137912,-0.059895,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
3,0.136500,0.054356,0.197496,-0.197704,0.006360,0.095166,0.294414,-0.119811,-0.140556,-0.061106,...,-0.005631,0.002488,-0.013618,-0.008738,0.007777,0.005095,0.00378,-0.015584,-0.005586,0.004156
4,0.142788,0.056305,0.189424,-0.201555,-0.013034,0.092953,0.297049,-0.125309,-0.132579,-0.069931,...,0.003815,-0.553314,0.003378,0.335591,0.143528,-1.134055,0.62961,0.330191,0.377519,-0.798777

#### 导入节点的GCN_Embedding

In [13]:
GCN_data = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/Emdebding_GCN.csv',header=None)
GCN_data.head()
len(GCN_data)

1619

In [15]:
# 导入节点的Embedding_DeepWalk
E_filename = 'C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/Embedding_grarep.txt'
Embedding_Node2vec = pd.read_csv(E_filename,sep=' ',header=None)
Embedding_Node2vec = Embedding_Node2vec.sort_values(0,ascending=True)# 建立序号排序
Embedding_Node2vec.reset_index(drop=True, inplace=True) 
Embedding_Node2vec = Embedding_Node2vec.iloc[:,1:]
Embedding_Node2vec[:10]
print(len(Embedding_Node2vec))

1619

### 训练模型

#### 生成负样本

In [16]:
def NegativeGenerate(LncDisease, AllRNA, AllDisease, num):
    # 负样本为全部的disease-rna（328*881）中随机抽取，未在内LncDisease即为负样本
    import random
    NegativeSample = []
    counterN = 0
    while counterN < len(num):  # 随机选出一个疾病rna对
        counterR = random.randint(0, len(AllRNA) - 1)
        counterD = random.randint(0, len(AllDisease) - 1)
        DiseaseAndRnaPair = []
        DiseaseAndRnaPair.append(AllRNA[counterR])
        DiseaseAndRnaPair.append(AllDisease[counterD])
        flag1 = 0
        counter = 0
        while counter < len(num):
            if DiseaseAndRnaPair == LncDisease[counter]:
                flag1 = 1
                break
            counter = counter + 1
        if flag1 == 1:
            continue
        flag2 = 0
        counter1 = 0
        while counter1 < len(NegativeSample):  # 在已选的负样本中没有，防止重复
            if DiseaseAndRnaPair == NegativeSample[counter1]:
                flag2 = 1
                break
            counter1 = counter1 + 1
        if flag2 == 1:
            continue
        if (flag1 == 0 & flag2 == 0):
            NamePair = []  # 生成对
            NamePair.append(AllRNA[counterR])
            NamePair.append(AllDisease[counterD])
            NegativeSample.append(NamePair)
            counterN = counterN + 1
    return NegativeSample
Dr = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/data/drug_name.csv',header=0,names=['id','name'])
Pr = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/data/protein_name.csv',header=0,names=['id','name'])
alldata = DTIs.append(Case_data) # 添加了测试集中关系对，保证所生产的负样本不包含测试集
NegativeSample = NegativeGenerate(alldata.values.tolist(),Dr['id'].values.tolist(),Pr['id'].values.tolist(),DTIs)
NegativeSample = pd.DataFrame(NegativeSample)
NegativeSample.to_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/NegativeSample.csv', header=None,index=False)
NegativeSample.head()

     0     1
0  916  1309
1  292  1050
2  857   994
3  135  1612
4  335  1168

In [17]:
data_vec = []
Negative = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/NegativeSample.csv',header=None)
Negative[2] = Negative.apply(lambda x: 0 if x[0] < 0 else 0, axis=1)
DTIs[2] = DTIs.apply(lambda x: 1 if x[0] < 0 else 1, axis=1)
result = DTIs.append(Negative)
labels = result[2]
train_data = result[[0,1]]
for i,j in np.array(train_data):
    data_vec.append(np.hstack([np.hstack([np.array(GCN_data.iloc[i]),np.array(Embedding_Node2vec.iloc[i])]),np.hstack([np.array(GCN_data.iloc[j]),np.array(Embedding_Node2vec.iloc[j])])]))
del Negative, train_data
np.array(data_vec).shape

(22792, 416)

In [21]:
from sklearn.ensemble import RandomForestClassifier
import joblib
case_RandomF = RandomForestClassifier(n_jobs=-1)# 选择最优的K=3传入模型
print('开始训练')#训练模型L
case_RandomF.fit(np.array(data_vec), np.array(labels))
# 保存模型
joblib.dump(case_RandomF,'C:/Users/HUAWEI/Desktop/DPIs/casestudy/XGB.pkl')
print('保存完毕')

开始训练
保存完毕

### 数据向量化

#### 导入test数据

In [22]:
import pandas as pd
case_data = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/Casestudy_Num_all.csv',header=None)
case_data.head()

    0    1
0  10  984
1  10  985
2  10  986
3  10  987
4  10  988

In [23]:
import numpy as np
Case_vectort = []
for i,j in np.array(case_data):#case_data
    Case_vectort.append(np.hstack([np.hstack([np.array(GCN_data.iloc[i]),np.array(Embedding_Node2vec.iloc[i])]),np.hstack([np.array(GCN_data.iloc[j]),np.array(Embedding_Node2vec.iloc[j])])]))
np.array(Case_vectort).shape

(614569, 416)

### 导入模型

In [26]:
import joblib
model = joblib.load('C:/Users/HUAWEI/Desktop/DPIs/casestudy/XGB.pkl')
y_score_GBDT = model.predict_proba(np.array(Case_vectort))
print('预测完毕！')

预测完毕！

In [27]:
y_score_GBDT

array([[0.72      , 0.28      ],
       [0.77      , 0.23      ],
       [0.584     , 0.416     ],
       ...,
       [0.74      , 0.26      ],
       [0.79333333, 0.20666667],
       [0.99      , 0.01      ]])

### 保存数据

In [28]:
# ID 转 Name
import pandas as pd
drug_name = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/data/drug_name.csv')
drug_name = drug_name.rename(columns={'Unnamed: 0': 'DrugID'})
drug_name.head()

   DrugID     drug
0       0  db00036
1       1  db00039
2       2  db00056
3       3  db00071
4       4  db00091

In [29]:
protein_name = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/data/protein_name.csv')
protein_name = protein_name.rename(columns={'Unnamed: 0': 'PrID'})
protein_name.head()

   PrID               protein
0   984  9606.ensp00000364709
1   985  9606.ensp00000364731
2   986  9606.ensp00000233838
3   987  9606.ensp00000410294
4   988  9606.ensp00000393312

In [30]:
col_name = ['DrugID','PrID']
case_data.columns = col_name
case_data.head()

   DrugID  PrID
0      10   984
1      10   985
2      10   986
3      10   987
4      10   988

In [31]:
dd = pd.merge(case_data,protein_name,how='left',on='PrID')
dd.head()

   DrugID  PrID               protein
0      10   984  9606.ensp00000364709
1      10   985  9606.ensp00000364731
2      10   986  9606.ensp00000233838
3      10   987  9606.ensp00000410294
4      10   988  9606.ensp00000393312

In [32]:
dd2 = pd.merge(dd,drug_name,how='left',on='DrugID')
dd2.head()

   DrugID  PrID               protein     drug
0      10   984  9606.ensp00000364709  db00120
1      10   985  9606.ensp00000364731  db00120
2      10   986  9606.ensp00000233838  db00120
3      10   987  9606.ensp00000410294  db00120
4      10   988  9606.ensp00000393312  db00120

In [37]:
drug = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/drug.csv')
drug.head()

,drug_id,name,drugbank_id,pubchem_cid,alias
0,C012255,clobazam,DB00349,2789.0,clobazam#Frisium#HR 376#LM-2717#Onfi#Urbanyl
1,C030852,vinorelbine,DB00361,44424639.0,5'-nor-anhydrovinblastine#KW 2307#KW-2307#Nave...
2,C043211,carvedilol,DB01136,2585.0,BM 14190#BM-14190#carvedilol#carvedilol hydroc...
3,C044946,benazepril,DB00542,5362124.0,benazapril#benazepril#benazepril hydrochloride...
4,C045463,leflunomide,DB01097,3899.0,Arava#Aventis Behring Brand of Leflunomide#Ave...

In [38]:
dd2['prob'] = y_score_GBDT[:,1]
dd2[['drug','protein','prob']].to_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/results/CaseStudy_Prob_all.csv', index = False)
print("保存完毕！")

保存完毕！

#### 匹配蛋白质命名

In [39]:
import pandas as pd
dd = pd.read_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/results/CaseStudy_Prob_all.csv')
dd.head()

      drug               protein   prob
0  db00120  9606.ensp00000364709  0.280
1  db00120  9606.ensp00000364731  0.230
2  db00120  9606.ensp00000233838  0.416
3  db00120  9606.ensp00000410294  0.130
4  db00120  9606.ensp00000393312  0.140

In [41]:
df = pd.read_excel('C:/Users/HUAWEI/Desktop/DPIs/casestudy/data/uniprot-yourlist.xlsx')
df = df.rename(columns={'yourlist:M20210116A94466D2655679D1FD8953E075198DA82FDBA03': 'protein'})
df

D:\Users\HUAWEI\anaconda3\envs\cs_dpi\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,protein,Entry,Entry name,Status,Protein names,Gene names,Organism,Length
0,9606.ensp00000282841,O95749,GGPPS_HUMAN,reviewed,Geranylgeranyl pyrophosphate synthase (GGPP sy...,GGPS1,Homo sapiens (Human),300.0
1,9606.ensp00000359539,P17174,AATC_HUMAN,reviewed,"Aspartate aminotransferase, cytoplasmic (cAspA...",GOT1,Homo sapiens (Human),413.0
2,9606.ensp00000296511,P08758,ANXA5_HUMAN,reviewed,Annexin A5 (Anchorin CII) (Annexin V) (Annexin...,ANXA5 ANX5 ENX2 PP4,Homo sapiens (Human),320.0
3,9606.ensp00000378669,P04075,ALDOA_HUMAN,reviewed,Fructose-bisphosphate aldolase A (EC 4.1.2.13)...,ALDOA ALDA,Homo sapiens (Human),364.0
4,9606.ensp00000481450,P04746,AMYP_HUMAN,reviewed,"Pancreatic alpha-amylase (PA) (EC 3.2.1.1) (1,...",AMY2A,Homo sapiens (Human),511.0
...,...,...,...,...,...,...,...,...
615,9606.ensp00000260682,P11712,CP2C9_HUMAN,reviewed,Cytochrome P450 2C9 (EC 1.14.14.1) ((R)-limone...,CYP2C9 CYP2C10,Homo sapiens (Human),490.0
616,9606.ensp00000295897,P02768,ALBU_HUMAN,reviewed,Albumin,ALB GIG20 GIG42 PRO0903 PRO1708 PRO2044 PRO261...,Homo sapiens (Human),609.0
617,9606.ensp00000360317,P10632,CP2C8_HUMAN,reviewed,Cytochrome P450 2C8 (EC 1.14.14.1) (CYPIIC8) (...,CYP2C8,Homo sapiens (Human),490.0
618,9606.ensp00000342007,P05177,CP1A2_HUMAN,reviewed,Cytochrome P450 1A2 (EC 1.14.14.1) (CYPIA2) (C...,CYP1A2,Homo sapiens (Human),516.0
619,9606.ensp00000360372,P33261,CP2CJ_HUMAN,reviewed,Cytochrome P450 2C19 (EC 1.14.14.1) ((R)-limon...,CYP2C19,Homo sapiens (Human),490.0

In [42]:
ddf = pd.merge(dd,df,how='left',on='protein')
ddf.head()

,drug,protein,prob,Entry,Entry name,Status,Protein names,Gene names,Organism,Length
0,db00120,9606.ensp00000364709,0.280,P00742,FA10_HUMAN,reviewed,Coagulation factor X (EC 3.4.21.6) (Stuart fac...,F10,Homo sapiens (Human),488.0
1,db00120,9606.ensp00000364731,0.230,P08709,FA7_HUMAN,reviewed,Coagulation factor VII (EC 3.4.21.21) (Proconv...,F7,Homo sapiens (Human),466.0
2,db00120,9606.ensp00000233838,0.416,P38435,VKGC_HUMAN,reviewed,Vitamin K-dependent gamma-carboxylase (EC 4.1....,GGCX GC,Homo sapiens (Human),758.0
3,db00120,9606.ensp00000410294,0.130,P21802,FGFR2_HUMAN,reviewed,Fibroblast growth factor receptor 2 (FGFR-2) (...,FGFR2 BEK KGFR KSAM,Homo sapiens (Human),821.0
4,db00120,9606.ensp00000393312,0.140,P11362,FGFR1_HUMAN,reviewed,Fibroblast growth factor receptor 1 (FGFR-1) (...,FGFR1 BFGFR CEK FGFBR FLG FLT2 HBGFR,Homo sapiens (Human),822.0

In [43]:
ddf[['drug','protein','Entry name','Gene names','Protein names','prob']].to_csv('C:/Users/HUAWEI/Desktop/DPIs/casestudy/results/NewCaseStudy_Prob_all.csv', index = False)